apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: default
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook
  type: LoadBalancer
status:
  loadBalancer: {}
